zuramai/mazer

- CONTRIBUTING.md
when I hit the "Contribute" button at https://zuramai.github.io/mazer/demo/ I got Github 404 not found, which is because there is no CONTRIBUTING.md file, I need you to add it.
I hope this helps.
> :memo: create CONTRIBUTING.md

- dist/assets/js/main.js
https://user-images.githubusercontent.com/50759463/106391532-6a4b8f80-6420-11eb-826f-141c2c28e7c7.mp4
> fix(sidebar): submenu bug in first click at submenu item url

- src/component-carousel.html
- src/form-editor-ckeditor.html
- src/form-editor-summernote.html
- src/form-element-textarea.html
- src/layout-horizontal.html
- src/ui-map-jsvectormap.html
> fix: wrong active position of some sidebar items

- README.md
fix vowel https://www.englishpage.com/articles/a-vs-an.htm
> fix a / an vowel

- README.md
i made boilerplate framework starter kit in adonisjs. please review it.
> add framework boilerplate starter kit: adonisjs

- .github/workflows/stale.yml
Add new labels for mazer and add stale bot
> build: add stale bot

- src/form-element-select.html
Hello, looks like choices.js changed their url. This PR fixes the choices.js url to the github repository.
> Fix choices.js url

- CONTRIBUTING.md
- README.md
I started updating the README and CONTRIBUTING files to better reflect the 2.0 changes
> Update readme and contributing guide

- src/assets/scss/themes/dark/_mazer-dark.scss
maybe it's can close issue #85
> fix: Feedback message not showing properly in dark mode

- package-lock.json
- src/assets/scss/components/_card.scss
- src/assets/scss/themes/dark/_mazer-dark.scss
- yarn.lock
i delete a box shadow and border of card pricing in dark mode, and change a color of card-text pricing highlight to white and change the icon color to teal using the scss variable.
i create a pull request to branch main.
feel free to discuss if there a mistake i make, thanks
> style: remove border and box-shadow card pricing in dark mode, change color of card highlight in light mode

- .dockerignore
- Dockerfile
- README.md
A PR for: https://github.com/zuramai/mazer/issues/111
Dockerizing mazer with Nginx support
> Docker support with Nginx

- src/component-card.html
> Add Social Media Card under Video Card on Components Layouts

- src/form-validation-parsley.html
I think we need to add some description in the form validation section.
> docs: edit form validation description

- src/assets/js/bootstrap.js
- src/assets/js/components/dark.js
- src/assets/js/initTheme.js
- src/layouts/master.html
Fix flickering dark mode.
This is not a typical solution for me but it's works.
Please using squash for merge.
Closes #118
> fix: flickering dark mode theme, closes #118

- src/form-validation-parsley.html
fix form validation page input
Before : 
After :
> fix(form-validation): form validation input

- README.md
> docs: add a dot in Donation

- README_INDONESIAN.md
Perbaikan terjemahan di readme_indonesian.md
> Update readme indonesian

- src/component-card.html
Fix UI bug and unoptimized classes from #134
> fix: social media card

- src/component-card.html
- src/ui-widgets-pricing.html
> add amet and dots

- src/component-carousel.html
fix: adding third slide on Carousel Item
> fix: adding third slide on Carousel Item

- README.md
Symfony 6 with webpack-encore + Mazer boilerplate
> docs: add symfony-mazer

- package.json
- src/assets/js/pages/jsvectormap.js
- src/ui-map-jsvectormap.html
- webpack.mix.js
Hi!, I just made UI for a vector map using the jsvectormap dependency, I think the UI of this plugin is perfect for this template. Hope it helps, anw sorry i closed PR before, cause there's a strange user commit name.
> feat: add ui jsvectormap

- README.md
> Add Ruby on Rails to Community Mazer-based open sources

- src/form-element-input.html
- yarn.lock
I just fix input button's id. So it can be clicked with the label.
> fix: input readonly's id

- src/component-alert.html
- src/component-dropdown.html
- src/component-list-group.html
- src/component-modal.html
- src/component-tooltip.html
- src/ui-widgets-chatbox.html
- src/ui-widgets-todolist.html
Fix some weird UIs and their own typography.
> fix: style and ui

- README.md
- README_INDONESIAN.md
I made a mazer boilerplate using Nextjs 13. You can give it try and give feedback :)
> Add next-mazer to readme

- src/application-email.html
As according to #236 
The email application page is broken because overflow element is showing which make the page have a scrollbar that make the page it not responsive. I also notice the page doesn't have toggle to show/hide the new compose element, i also i added it.
> Fix email application

- src/assets/static/js/components/sidebar.js
**Before** : 
https://github.com/zuramai/mazer/assets/27264641/475ff02a-4838-4dfe-8fb0-363d0907aa04
**After** : 
https://github.com/zuramai/mazer/assets/27264641/8a38f6d0-4a8c-495c-8d0c-363a99cabaf0
May be related to this bug issue https://github.com/zuramai/mazer/issues/122#issuecomment-1305192534
> Fix Sidebar - Vertical Layout with Navbar

- README.md
I made a laravel mazer starter kit. Using laravel 10 and the latest version of mazer. This is a further development of [Laravel Mazer](https://github.com/zuramai/laravel-mazer). You can give me feedback :D
> Change laravel mazer repostory

- README.md
- src/account-profile.html
- src/assets/scss/components/_avatar.scss
- src/sidebar-items.json
Hi, I created an account profile page. The page is inspired by the design of [SB Admin Pro](https://startbootstrap.com/previews/sb-admin-pro). Please give me feedback :)
What do I do?
1. Create a profile account page
2. Added 2xl and 3xl avatars to scss
3. Add pages to the sidebar navigation
Avatar size
```
xl = 60px
2xl = 60px * 2 = 120px
3xp = 60 * 3 = 180px
```
> Add page account profile

- src/assets/static/js/pages/dashboard.js
- src/index.html
- src/layout-horizontal.html
- src/layout-rtl-backup.html
- src/layout-rtl.html
- yarn.lock
In this commit, I have added a Profile visit card for India
> Added India profile visit card

- src/account-profile.html
- src/account-security.html
- src/sidebar-items.json
What do I do?
1. Create an account security page
2. Add account security to the sidebar menu
What was fixed?
1. Removed the Upload Image button
2. Added birthday date input
3. Added gender selection input
4. Add name and bio below profile photo
> Add page account security and update page account profile

- src/assets/scss/_mazer.scss
- src/assets/scss/_variables.scss
- src/assets/scss/components/_placeholders.scss
- src/component-placeholder.html
- src/sidebar-items.json
- yarn.lock
Placeholders are an original component of Bootstrap. Placeholders are used to improve user experience, they can also be used for display when loading a page.
Inspired by native bootstrap components, click here https://getbootstrap.com/docs/5.3/components/placeholders/
This placeholder was created only with HTML and CSS, you don't need Javascript to create a placeholder, just use HTML and CSS. Javascript is used as a visibility toggle only.
See screenshot
> Add placeholder component

- README.md
- README_INDONESIAN.md
Hi, I added CDN usage to the mazer template, and I also added CDN usage in Indonesian
> Added CDN to readme

- src/assets/static/js/components/sidebar.js
closes https://github.com/zuramai/mazer/issues/278
> Fix sidebar crashing when no elements are active

- src/assets/static/js/pages/ui-map-leaflet.js
- src/sidebar-items.json
- src/ui-map-leaflet.html
> add leaflet map ui

- src/sidebar-items.json
- yarn.lock
the donate link is directly  sponser in git hub for direct doanting via a sponser
> changes to the donate link to git hub sponser direct
