zuramai/mazer

src/assets/scss/components/_sidebar.scss
src/table.html

Fixed spelling error of "documentation".
Fixed .table-responsive should be added to surrounding div, not to the table itself.
https://getbootstrap.com/docs/5.0/content/tables/

Fix spelling error, fix table-responsive class help text

---

src/assets/scss/_variables.scss

Hello, I have fixed the problem no difference in placeholder color and the text color.  Can you check my pull request? Please find the difference in attached image.

Fixed a difference in placeholder color and the text color. 

---

src/assets/scss/_variables.scss

Hello, I found following CSS variables not updated due theme colors and have BS default values.
```
--bs-primary-rgb: 13,110,253;
--bs-secondary-rgb: 108,117,125;
--bs-success-rgb: 25,135,84;
--bs-info-rgb: 13,202,240;
--bs-warning-rgb: 255,193,7;
--bs-danger-rgb: 220,53,69;
--bs-light-rgb: 248,249,250;
--bs-dark-rgb: 33,37,41;
--bs-white-rgb: 255,255,255;
--bs-black-rgb: 0,0,0;
--bs-body-color-rgb: 96,112,128;
--bs-body-bg-rgb: 242,247,255;
```
Impact of that theme colors not work properly. For example bg-primary. You can check it [mazer/dist/component-modal.html](https://github.com/zuramai/mazer/blob/main/dist/component-modal.html). Please find the attachment image.

fix: updating $theme-color-rgb css variable.

---

src/assets/js/components/sidebar.js

I got some errors in my frontend error handler related to the sidebar.
In some situations I don't have an active menu item.

Prevent sidebar from throwing errors when there is no active item

---

src/assets/js/components/sidebar.js

If the user opens a submenu in the sidebar located at the bottom of the viewport, he will need to manually the opening menu into view.
I implemented a quick autoscroll functionality which scrolls the submenu into view after opening it.
This is not an optimal solution as it has to wait for the opening animation to complete.
The `slideToggle` function is hard to modify as the function code is minified.

Autoscroll when opening submenus in sidebar

---

dist/layout-vertical-navbar.html
src/assets/js/components/sidebar.js
src/assets/scss/components/_dropdowns.scss

The dropdown caret color is set to white on all dropdowns.
Negative implications of this can be observed in the "Vertical Navbar" demo.
After looking through the code I think all dropdown examples use buttons where the white color works great.
I changed the definition to only affect caret color in buttons.
Light buttons and outline button should be excluded as well imho.

Only force white caret on button dropdowns

---

dist/assets/js/pages/horizontal-layout.js

if a user makes the screen smaller than 1200, they can click the "burger" button to open and close the nav. if they then enlarge the window after closing it, the nav will still be hidden. this pr fixes that by removing the `display: none` when being resized above 1200

Fixed nav being hidden if resized after being clicked on in horizontal-layout

---

dist/.gitignore
src/assets/js/components/dark.js
src/assets/js/extensions/tinymce.js
src/assets/scss/pages/auth.scss
src/assets/scss/pages/email.scss
src/assets/scss/pages/error.scss
src/assets/scss/themes/dark/_root.scss
src/assets/scss/themes/dark/app-dark.scss
src/layouts/master.html
src/layouts/rtl.html
src/layouts/vertical-navbar.html

Some improvements for dark theme support
- Use the DOMContentLoaded event instead of "load" because the theme will apply while the site is still potentially loading resources. This prevents some "flickering" from light to dark on page change.
- Apply theme based on the local storage setting. If the setting is missing (and only then), respect "prefers-color-scheme" to set a theme, but skip persisting.
- Swaps the theme via a listener if prefers-color-scheme changes (if theme is not pinned)
-Apply dark theme stuff to body.theme-dark {} instead of .theme-dark {} only because the class name is pretty generic.
- Don't clear out body classes because users might use other classes on body. Instead, use regex to remove existing theme classes.
- Auto dark-theme for tinymce

Theme handling improvements

---

src/component-dropdown.html

Test Flow
1. Go to the dropdown menu page in components
2. In the variations section there is typo sepration, which should be separation

fix: change typo separation on dropdown

---

src/component-dropdown.html

Seeing the form password using capitalize text for placeholder and the form email is not using capitalize text i think is uncomfortable too seeing it xD

Capitalize placeholder text

---

src/ui-chart-chartjs.html

in page charts/chartjs, chart not showing, because there is an error in the chartjs file source caused by case sensitive

fix: case sensitive chartjs

---

src/ui-map-google-map.html

- Fix google maps iframe width to 100% at src/ui-map-google-map.html

fix: google maps iframe width to 100%

---

src/assets/scss/bootstrap.scss

Hello,
I encountered a little problem with Webpack Encore (Provided with Symfony).
I found @import "~bootstrap/scss/functions"; not imported in bootstrap.scss.

fix: import of functions.scss in bootstrap.scss

---

src/extra-component-avatar.html

I have been fixed text highlighted class .avatar-content on docs
before:

docs: fix text highlighted on .avatar-content

---

src/error-500.html

Title in error-500.html should be 500, not 405 I guess.

fix: error-500.html title

---

src/assets/scss/components/_sidebar.scss

The color value with # breaks building/minifying in symfony project with webpack-encore-bundle `Error: SvgoParserError: <input>:1:259: Unquoted attribute value`. Beyond that the value with # is an inconsistency as the other two values in line 85 and line 96 are `grey` and `white`.

fix: changed svg color value from #fff to white

---

src/assets/scss/components/_table.scss
src/assets/static/js/pages/filepond.js

I just fix simple datatable's padding and also make fileponds becomes file-able.

fix datatable and filepond 

---

README.md

Hey
I purpose a Symfony with Webpack Encore with latest version of Symfony (6.3) that is currently in development (release planned to be in May 2023)
[Repository URL](https://github.com/TheoD02/mazer-symfony-6.3/tree/mazer-2.1.0)
All layouts it's implemented
Access to Front and Back controller ready to go
Error page are supported by default with App\Core\Http\Listener\ExceptionListener on kernel.exception Default locale in URL ready (fr/en by default)
No README for the moment, I will make it soon 👍

Add Symfony 6.3 with latest Mazer version

---

src/assets/static/js/components/sidebar.js

Current build default layout sidebar and main gets overlapped if the browser size gets small and the sidebar show button clicked then the browser gets bigger again.

current build default layout sidebar and main gets overlapped

---

src/assets/static/js/components/sidebar.js

Make sidebar method as a global function, fix auto calculate height for submenus
Implement for some case if build SPA application, that sidebar can't reinitialize
**how to use**
```javascript
const sidebar = new window.Sidebar(document.getElementById("sidebar"), {
recalculateHeight: true
})
```
Patch for issue https://github.com/zuramai/mazer/issues/257#issuecomment-1740480979

Fix sidebar initialize & dropdown smooth

---

src/component-card.html

I have fixed the information in the card section of the Components folder
Before:
After:

fixed information in Components/Card

---

src/assets/scss/components/_alert.scss

This fixes a visual bug which made the "Close" button on dismissable alerts hard to see or invisible in some cases (e.g. the black X icon in the alert-dark component).
- Light mode:
- Dark mode:
- Light mode:
- Dark mode:
This doesn't seem to fully work yet... Any help is appreciated

Fix Alert "close" button colors on dark/light backgrounds

---

src/assets/scss/pages/sweetalert2.scss
src/extra-component-sweetalert.html

Hi, I have fixed a bug in sweetalert2 input. The bug is like the one in the screenshot. #268 
The result is like this
What do I do?
1. Add a new scss file to the path `assets/scss/pages/sweetalert2.scss`
2. Change the width of the .form-control to the initial value

Fix sweetalert2 input long size

---

src/assets/scss/_variables.scss
src/assets/scss/components/_buttons.scss

The button colors defined in `_variables.scss` are currently not applied due to a bug in `_buttons.scss`.
I fixed the bug in _buttons.scss and changed the colors set in _variables.scss to match the currently active colors, which are determined by bootstraps default functionality.
We should either adapt this change or remove the `btn-colors` sections from `_variables.scss` and `_buttons.scss`.

Fix button colors in _variables.scss not being applied
